# Copyright 2025 Stack AV Co.
# SPDX-License-Identifier: Apache-2.0

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: no-commit-to-branch
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix, lf]
    - id: trailing-whitespace
    - id: check-toml
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort

- repo: https://github.com/google/addlicense
  rev: 499ed7f28389eb4a08c2d7e40b1637cfd7f65381 # master
  hooks:
    - id: addlicense
      args: ["-c=Stack AV Co.", "-l=Apache-2.0", "-s=only"]
      exclude: |
        (?x)^(
          |conch/third_party/.*
        )$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.17.2
  hooks:
    - id: markdownlint-cli2

- repo: local
  hooks:
    - id: mypy-local
      name: mypy-local
      entry: ./tools/mypy.sh
      language: system
      files: \.py$
